"""remove is_control_stock product

Revision ID: 4b168d55a245
Revises: 885511c80053
Create Date: 2026-06-02 08:22:31.592399

"""
from typing import Sequence, Union
from app.scripts.tenant import for_each_tenant_schema
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b168d55a245'
down_revision: Union[str, Sequence[str], None] = '885511c80053'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

@for_each_tenant_schema
def upgrade(schema: str) -> None:
    """Upgrade schema."""
    preparer = sa.sql.compiler.IdentifierPreparer(op.get_bind().dialect)
    schema_quoted = preparer.format_schema(schema)
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_control_stock', schema=schema)
    # ### end Alembic commands ###


@for_each_tenant_schema
def downgrade(schema: str) -> None:
    """Downgrade schema."""
    preparer = sa.sql.compiler.IdentifierPreparer(op.get_bind().dialect)
    schema_quoted = preparer.format_schema(schema)
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_control_stock', sa.BOOLEAN(), autoincrement=False, nullable=False), schema=schema)
    # ### end Alembic commands ###
