"""unit_measure schema

Revision ID: 5b988b30a960
Revises: feb69219c6a5
Create Date: 2026-06-01 16:24:53.483915

"""
from typing import Sequence, Union
from app.scripts.tenant import for_each_tenant_schema
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b988b30a960'
down_revision: Union[str, Sequence[str], None] = 'feb69219c6a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

@for_each_tenant_schema
def upgrade(schema: str) -> None:
    """Upgrade schema."""
    preparer = sa.sql.compiler.IdentifierPreparer(op.get_bind().dialect)
    schema_quoted = preparer.format_schema(schema)
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unit_measures',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('abbreviation', sa.String(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique record identifier'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Record creation time'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Unique record identifier'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__unit_measures')),
    schema=schema
    )
    op.create_index(op.f('ix__unit_measures__abbreviation'), 'unit_measures', ['abbreviation'], unique=True, schema=schema)
    # ### end Alembic commands ###


@for_each_tenant_schema
def downgrade(schema: str) -> None:
    """Downgrade schema."""
    preparer = sa.sql.compiler.IdentifierPreparer(op.get_bind().dialect)
    schema_quoted = preparer.format_schema(schema)
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__unit_measures__abbreviation'), table_name='unit_measures', schema=schema)
    op.drop_table('unit_measures', schema=schema)
    # ### end Alembic commands ###
