"""table schema

Revision ID: 71fe49f8a266
Revises: 459a561cfe82
Create Date: 2026-06-01 20:28:28.079747

"""
from typing import Sequence, Union
from app.scripts.tenant import for_each_tenant_schema
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '71fe49f8a266'
down_revision: Union[str, Sequence[str], None] = '459a561cfe82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

@for_each_tenant_schema
def upgrade(schema: str) -> None:
    """Upgrade schema."""
    preparer = sa.sql.compiler.IdentifierPreparer(op.get_bind().dialect)
    schema_quoted = preparer.format_schema(schema)
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tables',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('qr_code', sa.String(length=255), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique record identifier'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Record creation time'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Unique record identifier'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__tables')),
    schema=schema
    )
    op.create_index(op.f('ix__tables__qr_code'), 'tables', ['qr_code'], unique=True, schema=schema)
   
    # ### end Alembic commands ###


@for_each_tenant_schema
def downgrade(schema: str) -> None:
    """Downgrade schema."""
    preparer = sa.sql.compiler.IdentifierPreparer(op.get_bind().dialect)
    schema_quoted = preparer.format_schema(schema)
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__tables__qr_code'), table_name='tables', schema=schema)
    op.drop_table('tables', schema=schema)
    # ### end Alembic commands ###
