"""inventory schema

Revision ID: 752fe2608b73
Revises: 71fe49f8a266
Create Date: 2026-06-02 08:19:33.000304

"""
from typing import Sequence, Union
from app.scripts.tenant import for_each_tenant_schema
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '752fe2608b73'
down_revision: Union[str, Sequence[str], None] = '71fe49f8a266'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

@for_each_tenant_schema
def upgrade(schema: str) -> None:
    """Upgrade schema."""
    preparer = sa.sql.compiler.IdentifierPreparer(op.get_bind().dialect)
    schema_quoted = preparer.format_schema(schema)
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory',
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique record identifier'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Record creation time'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Unique record identifier'),
    sa.ForeignKeyConstraint(['product_id'], [f'{schema}.products.id'], name=op.f('fk__inventory__product_id__products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__inventory')),
    schema=schema
    )
    # ### end Alembic commands ###


@for_each_tenant_schema
def downgrade(schema: str) -> None:
    """Downgrade schema."""
    preparer = sa.sql.compiler.IdentifierPreparer(op.get_bind().dialect)
    schema_quoted = preparer.format_schema(schema)
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory', schema=schema)
    # ### end Alembic commands ###
