"""baseline heladeria simple

Revision ID: ca3b1684ba9d
Revises: 
Create Date: 2026-07-12 12:32:54.674579

"""
from typing import Sequence, Union
from app.scripts.tenant import for_each_tenant_schema
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca3b1684ba9d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

@for_each_tenant_schema
def upgrade(schema: str) -> None:
    """Upgrade schema."""
    preparer = sa.sql.compiler.IdentifierPreparer(op.get_bind().dialect)
    schema_quoted = preparer.format_schema(schema)
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_registers',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique record identifier'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__cash_registers')),
    sa.UniqueConstraint('name', name=op.f('uq__cash_registers__name')),
    schema=schema
    )
    op.create_table('categories',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique record identifier'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Record creation time'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Unique record identifier'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__categories')),
    schema=schema
    )
    op.create_index(op.f('ix__categories__name'), 'categories', ['name'], unique=True, schema=schema)
    op.create_table('dining_tables',
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('qr_token', sa.UUID(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique record identifier'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__dining_tables')),
    sa.UniqueConstraint('number', name=op.f('uq__dining_tables__number')),
    sa.UniqueConstraint('qr_token', name=op.f('uq__dining_tables__qr_token')),
    schema=schema
    )
    op.create_table('option_groups',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('min_select', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_select', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique record identifier'),
    sa.CheckConstraint('max_select >= min_select', name=op.f('ck__option_groups__ck_option_group_max_ge_min')),
    sa.CheckConstraint('min_select >= 0', name=op.f('ck__option_groups__ck_option_group_min_select')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__option_groups')),
    sa.UniqueConstraint('name', name=op.f('uq__option_groups__name')),
    schema=schema
    )
    op.create_table('payment_methods',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_cash', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique record identifier'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__payment_methods')),
    sa.UniqueConstraint('name', name=op.f('uq__payment_methods__name')),
    schema=schema
    )
    op.create_table('suppliers',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tax_id', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique record identifier'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Record creation time'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Unique record identifier'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__suppliers')),
    schema=schema
    )
    op.create_table('unit_measures',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('abbreviation', sa.String(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique record identifier'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Record creation time'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Unique record identifier'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__unit_measures')),
    sa.UniqueConstraint('name', name=op.f('uq__unit_measures__name')),
    schema=schema
    )
    op.create_index(op.f('ix__unit_measures__abbreviation'), 'unit_measures', ['abbreviation'], unique=True, schema=schema)
    op.create_table('cash_shifts',
    sa.Column('cash_register_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('opening_amount', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('opened_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('counted_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=10), server_default='open', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique record identifier'),
    sa.CheckConstraint("status = 'open' OR closed_at IS NOT NULL", name=op.f('ck__cash_shifts__ck_cash_shift_closed_has_timestamp')),
    sa.CheckConstraint("status IN ('open', 'closed')", name=op.f('ck__cash_shifts__ck_cash_shift_status')),
    sa.CheckConstraint('opening_amount >= 0', name=op.f('ck__cash_shifts__ck_cash_shift_opening_positive')),
    sa.ForeignKeyConstraint(['cash_register_id'], ['tenant_default.cash_registers.id'], name=op.f('fk__cash_shifts__cash_register_id__cash_registers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__cash_shifts')),
    schema=schema
    )
    op.create_index('idx_open_shift_per_register', 'cash_shifts', ['cash_register_id'], unique=True, schema=schema, postgresql_where=sa.text("status = 'open'"))
    op.create_index(op.f('ix__cash_shifts__cash_register_id'), 'cash_shifts', ['cash_register_id'], unique=False, schema=schema)
    op.create_table('dining_sessions',
    sa.Column('dining_table_id', sa.UUID(), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=10), server_default='open', nullable=False),
    sa.Column('opened_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique record identifier'),
    sa.CheckConstraint("status IN ('open', 'closed')", name=op.f('ck__dining_sessions__ck_dining_session_status')),
    sa.ForeignKeyConstraint(['dining_table_id'], ['tenant_default.dining_tables.id'], name=op.f('fk__dining_sessions__dining_table_id__dining_tables')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__dining_sessions')),
    schema=schema
    )
    op.create_index('idx_open_session_per_table', 'dining_sessions', ['dining_table_id'], unique=True, schema=schema, postgresql_where=sa.text("status = 'open'"))
    op.create_index(op.f('ix__dining_sessions__dining_table_id'), 'dining_sessions', ['dining_table_id'], unique=False, schema=schema)
    op.create_table('inventory_items',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('unit_measure_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=20), server_default='raw_material', nullable=False),
    sa.Column('current_stock', sa.Numeric(precision=12, scale=3), server_default='0', nullable=False),
    sa.Column('min_stock', sa.Numeric(precision=12, scale=3), server_default='0', nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique record identifier'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Record creation time'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Unique record identifier'),
    sa.CheckConstraint("type IN ('raw_material', 'packaged')", name=op.f('ck__inventory_items__ck_inventory_item_type')),
    sa.ForeignKeyConstraint(['unit_measure_id'], ['tenant_default.unit_measures.id'], name=op.f('fk__inventory_items__unit_measure_id__unit_measures')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__inventory_items')),
    schema=schema
    )
    op.create_index(op.f('ix__inventory_items__name'), 'inventory_items', ['name'], unique=True, schema=schema)
    op.create_index(op.f('ix__inventory_items__unit_measure_id'), 'inventory_items', ['unit_measure_id'], unique=False, schema=schema)
    op.create_table('products',
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('preparation_type', sa.String(length=20), server_default='prepared', nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique record identifier'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Record creation time'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Unique record identifier'),
    sa.CheckConstraint("preparation_type IN ('prepared', 'packaged')", name=op.f('ck__products__ck_product_preparation_type')),
    sa.ForeignKeyConstraint(['category_id'], ['tenant_default.categories.id'], name=op.f('fk__products__category_id__categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__products')),
    sa.UniqueConstraint('category_id', 'name', name='uq__products__category_id__name'),
    schema=schema
    )
    op.create_index(op.f('ix__products__category_id'), 'products', ['category_id'], unique=False, schema=schema)
    op.create_table('purchases',
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('total', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('purchased_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique record identifier'),
    sa.ForeignKeyConstraint(['supplier_id'], ['tenant_default.suppliers.id'], name=op.f('fk__purchases__supplier_id__suppliers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__purchases')),
    schema=schema
    )
    op.create_index(op.f('ix__purchases__supplier_id'), 'purchases', ['supplier_id'], unique=False, schema=schema)
    op.create_table('cash_count_denominations',
    sa.Column('cash_shift_id', sa.UUID(), nullable=False),
    sa.Column('denomination', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique record identifier'),
    sa.CheckConstraint('denomination > 0', name=op.f('ck__cash_count_denominations__ck_cash_count_denomination_positive')),
    sa.CheckConstraint('quantity >= 0', name=op.f('ck__cash_count_denominations__ck_cash_count_quantity_positive')),
    sa.ForeignKeyConstraint(['cash_shift_id'], ['tenant_default.cash_shifts.id'], name=op.f('fk__cash_count_denominations__cash_shift_id__cash_shifts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__cash_count_denominations')),
    sa.UniqueConstraint('cash_shift_id', 'denomination', name='uq__cash_count_denominations__cash_shift_id__denomination'),
    schema=schema
    )
    op.create_index(op.f('ix__cash_count_denominations__cash_shift_id'), 'cash_count_denominations', ['cash_shift_id'], unique=False, schema=schema)
    op.create_table('cash_movements',
    sa.Column('cash_shift_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique record identifier'),
    sa.CheckConstraint("type IN ('in', 'out')", name=op.f('ck__cash_movements__ck_cash_movement_type')),
    sa.CheckConstraint('amount > 0', name=op.f('ck__cash_movements__ck_cash_movement_amount_positive')),
    sa.ForeignKeyConstraint(['cash_shift_id'], ['tenant_default.cash_shifts.id'], name=op.f('fk__cash_movements__cash_shift_id__cash_shifts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__cash_movements')),
    schema=schema
    )
    op.create_index(op.f('ix__cash_movements__cash_shift_id'), 'cash_movements', ['cash_shift_id'], unique=False, schema=schema)
    op.create_table('customer_orders',
    sa.Column('dining_session_id', sa.UUID(), nullable=True),
    sa.Column('dining_table_id', sa.UUID(), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('channel', sa.String(length=10), server_default='qr', nullable=False),
    sa.Column('status', sa.String(length=12), server_default='pending', nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique record identifier'),
    sa.CheckConstraint("channel IN ('qr', 'counter', 'waiter')", name=op.f('ck__customer_orders__ck_customer_order_channel')),
    sa.CheckConstraint("status IN ('pending', 'preparing', 'served', 'cancelled')", name=op.f('ck__customer_orders__ck_customer_order_status')),
    sa.ForeignKeyConstraint(['dining_session_id'], ['tenant_default.dining_sessions.id'], name=op.f('fk__customer_orders__dining_session_id__dining_sessions')),
    sa.ForeignKeyConstraint(['dining_table_id'], ['tenant_default.dining_tables.id'], name=op.f('fk__customer_orders__dining_table_id__dining_tables')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__customer_orders')),
    schema=schema
    )
    op.create_index(op.f('ix__customer_orders__dining_session_id'), 'customer_orders', ['dining_session_id'], unique=False, schema=schema)
    op.create_table('inventory_movements',
    sa.Column('inventory_item_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('moved_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique record identifier'),
    sa.CheckConstraint("type IN ('in', 'out', 'adjustment')", name=op.f('ck__inventory_movements__ck_inventory_movement_type')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck__inventory_movements__ck_inventory_movement_qty_positive')),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['tenant_default.inventory_items.id'], name=op.f('fk__inventory_movements__inventory_item_id__inventory_items')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__inventory_movements')),
    schema=schema
    )
    op.create_index('idx_invmov_ref', 'inventory_movements', ['reference_type', 'reference_id'], unique=False, schema=schema)
    op.create_index(op.f('ix__inventory_movements__inventory_item_id'), 'inventory_movements', ['inventory_item_id'], unique=False, schema=schema)
    op.create_table('options',
    sa.Column('option_group_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('extra_price', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('inventory_item_id', sa.UUID(), nullable=True),
    sa.Column('item_quantity', sa.Numeric(precision=12, scale=3), server_default='0', nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique record identifier'),
    sa.CheckConstraint('extra_price >= 0', name=op.f('ck__options__ck_option_extra_price_positive')),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['tenant_default.inventory_items.id'], name=op.f('fk__options__inventory_item_id__inventory_items')),
    sa.ForeignKeyConstraint(['option_group_id'], ['tenant_default.option_groups.id'], name=op.f('fk__options__option_group_id__option_groups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__options')),
    sa.UniqueConstraint('option_group_id', 'name', name='uq__options__option_group_id__name'),
    schema=schema
    )
    op.create_index(op.f('ix__options__option_group_id'), 'options', ['option_group_id'], unique=False, schema=schema)
    op.create_table('product_option_groups',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('option_group_id', sa.UUID(), nullable=False),
    sa.Column('min_select', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_select', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique record identifier'),
    sa.CheckConstraint('max_select >= min_select', name=op.f('ck__product_option_groups__ck_product_option_group_max_ge_min')),
    sa.ForeignKeyConstraint(['option_group_id'], ['tenant_default.option_groups.id'], name=op.f('fk__product_option_groups__option_group_id__option_groups')),
    sa.ForeignKeyConstraint(['product_id'], ['tenant_default.products.id'], name=op.f('fk__product_option_groups__product_id__products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__product_option_groups')),
    sa.UniqueConstraint('product_id', 'option_group_id', name='uq__product_option_groups__product_id__option_group_id'),
    schema=schema
    )
    op.create_index(op.f('ix__product_option_groups__option_group_id'), 'product_option_groups', ['option_group_id'], unique=False, schema=schema)
    op.create_index(op.f('ix__product_option_groups__product_id'), 'product_option_groups', ['product_id'], unique=False, schema=schema)
    op.create_table('product_variants',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), server_default='Single', nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique record identifier'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Record creation time'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Unique record identifier'),
    sa.CheckConstraint('price >= 0', name=op.f('ck__product_variants__ck_product_variant_price_positive')),
    sa.ForeignKeyConstraint(['product_id'], ['tenant_default.products.id'], name=op.f('fk__product_variants__product_id__products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__product_variants')),
    sa.UniqueConstraint('product_id', 'name', name='uq__product_variants__product_id__name'),
    sa.UniqueConstraint('sku', name=op.f('uq__product_variants__sku')),
    schema=schema
    )
    op.create_index(op.f('ix__product_variants__product_id'), 'product_variants', ['product_id'], unique=False, schema=schema)
    op.create_table('purchase_items',
    sa.Column('purchase_id', sa.UUID(), nullable=False),
    sa.Column('inventory_item_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique record identifier'),
    sa.CheckConstraint('quantity > 0', name=op.f('ck__purchase_items__ck_purchase_item_qty_positive')),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['tenant_default.inventory_items.id'], name=op.f('fk__purchase_items__inventory_item_id__inventory_items')),
    sa.ForeignKeyConstraint(['purchase_id'], ['tenant_default.purchases.id'], name=op.f('fk__purchase_items__purchase_id__purchases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__purchase_items')),
    schema=schema
    )
    op.create_index(op.f('ix__purchase_items__inventory_item_id'), 'purchase_items', ['inventory_item_id'], unique=False, schema=schema)
    op.create_index(op.f('ix__purchase_items__purchase_id'), 'purchase_items', ['purchase_id'], unique=False, schema=schema)
    op.create_table('sales',
    sa.Column('dining_session_id', sa.UUID(), nullable=True),
    sa.Column('dining_table_id', sa.UUID(), nullable=True),
    sa.Column('cash_shift_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('discount', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('tax', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('tip', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=10), server_default='issued', nullable=False),
    sa.Column('sold_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique record identifier'),
    sa.CheckConstraint("status IN ('issued', 'paid', 'void')", name=op.f('ck__sales__ck_sale_status')),
    sa.ForeignKeyConstraint(['cash_shift_id'], ['tenant_default.cash_shifts.id'], name=op.f('fk__sales__cash_shift_id__cash_shifts')),
    sa.ForeignKeyConstraint(['dining_session_id'], ['tenant_default.dining_sessions.id'], name=op.f('fk__sales__dining_session_id__dining_sessions')),
    sa.ForeignKeyConstraint(['dining_table_id'], ['tenant_default.dining_tables.id'], name=op.f('fk__sales__dining_table_id__dining_tables')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__sales')),
    schema=schema
    )
    op.create_index(op.f('ix__sales__cash_shift_id'), 'sales', ['cash_shift_id'], unique=False, schema=schema)
    op.create_table('order_items',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('product_variant_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique record identifier'),
    sa.CheckConstraint('quantity > 0', name=op.f('ck__order_items__ck_order_item_quantity_positive')),
    sa.ForeignKeyConstraint(['order_id'], ['tenant_default.customer_orders.id'], name=op.f('fk__order_items__order_id__customer_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_variant_id'], ['tenant_default.product_variants.id'], name=op.f('fk__order_items__product_variant_id__product_variants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__order_items')),
    schema=schema
    )
    op.create_index(op.f('ix__order_items__order_id'), 'order_items', ['order_id'], unique=False, schema=schema)
    op.create_index(op.f('ix__order_items__product_variant_id'), 'order_items', ['product_variant_id'], unique=False, schema=schema)
    op.create_table('payments',
    sa.Column('sale_id', sa.UUID(), nullable=False),
    sa.Column('payment_method_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('paid_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique record identifier'),
    sa.CheckConstraint('amount > 0', name=op.f('ck__payments__ck_payment_amount_positive')),
    sa.ForeignKeyConstraint(['payment_method_id'], ['tenant_default.payment_methods.id'], name=op.f('fk__payments__payment_method_id__payment_methods')),
    sa.ForeignKeyConstraint(['sale_id'], ['tenant_default.sales.id'], name=op.f('fk__payments__sale_id__sales'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__payments')),
    schema=schema
    )
    op.create_index(op.f('ix__payments__payment_method_id'), 'payments', ['payment_method_id'], unique=False, schema=schema)
    op.create_index(op.f('ix__payments__sale_id'), 'payments', ['sale_id'], unique=False, schema=schema)
    op.create_table('recipe_items',
    sa.Column('product_variant_id', sa.UUID(), nullable=False),
    sa.Column('inventory_item_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique record identifier'),
    sa.CheckConstraint('quantity > 0', name=op.f('ck__recipe_items__ck_recipe_item_qty_positive')),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['tenant_default.inventory_items.id'], name=op.f('fk__recipe_items__inventory_item_id__inventory_items')),
    sa.ForeignKeyConstraint(['product_variant_id'], ['tenant_default.product_variants.id'], name=op.f('fk__recipe_items__product_variant_id__product_variants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__recipe_items')),
    sa.UniqueConstraint('product_variant_id', 'inventory_item_id', name='uq__recipe_items__product_variant_id__inventory_item_id'),
    schema=schema
    )
    op.create_index(op.f('ix__recipe_items__inventory_item_id'), 'recipe_items', ['inventory_item_id'], unique=False, schema=schema)
    op.create_index(op.f('ix__recipe_items__product_variant_id'), 'recipe_items', ['product_variant_id'], unique=False, schema=schema)
    op.create_table('sale_items',
    sa.Column('sale_id', sa.UUID(), nullable=False),
    sa.Column('product_variant_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique record identifier'),
    sa.CheckConstraint('quantity > 0', name=op.f('ck__sale_items__ck_sale_item_quantity_positive')),
    sa.ForeignKeyConstraint(['product_variant_id'], ['tenant_default.product_variants.id'], name=op.f('fk__sale_items__product_variant_id__product_variants')),
    sa.ForeignKeyConstraint(['sale_id'], ['tenant_default.sales.id'], name=op.f('fk__sale_items__sale_id__sales'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__sale_items')),
    schema=schema
    )
    op.create_index(op.f('ix__sale_items__sale_id'), 'sale_items', ['sale_id'], unique=False, schema=schema)
    op.create_table('order_item_options',
    sa.Column('order_item_id', sa.UUID(), nullable=False),
    sa.Column('option_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique record identifier'),
    sa.ForeignKeyConstraint(['option_id'], ['tenant_default.options.id'], name=op.f('fk__order_item_options__option_id__options')),
    sa.ForeignKeyConstraint(['order_item_id'], ['tenant_default.order_items.id'], name=op.f('fk__order_item_options__order_item_id__order_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__order_item_options')),
    sa.UniqueConstraint('order_item_id', 'option_id', name='uq__order_item_options__order_item_id__option_id'),
    schema=schema
    )
    op.create_index(op.f('ix__order_item_options__option_id'), 'order_item_options', ['option_id'], unique=False, schema=schema)
    op.create_index(op.f('ix__order_item_options__order_item_id'), 'order_item_options', ['order_item_id'], unique=False, schema=schema)
    # ### end Alembic commands ###


@for_each_tenant_schema
def downgrade(schema: str) -> None:
    """Downgrade schema."""
    preparer = sa.sql.compiler.IdentifierPreparer(op.get_bind().dialect)
    schema_quoted = preparer.format_schema(schema)
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__order_item_options__order_item_id'), table_name='order_item_options', schema=schema)
    op.drop_index(op.f('ix__order_item_options__option_id'), table_name='order_item_options', schema=schema)
    op.drop_table('order_item_options', schema=schema)
    op.drop_index(op.f('ix__sale_items__sale_id'), table_name='sale_items', schema=schema)
    op.drop_table('sale_items', schema=schema)
    op.drop_index(op.f('ix__recipe_items__product_variant_id'), table_name='recipe_items', schema=schema)
    op.drop_index(op.f('ix__recipe_items__inventory_item_id'), table_name='recipe_items', schema=schema)
    op.drop_table('recipe_items', schema=schema)
    op.drop_index(op.f('ix__payments__sale_id'), table_name='payments', schema=schema)
    op.drop_index(op.f('ix__payments__payment_method_id'), table_name='payments', schema=schema)
    op.drop_table('payments', schema=schema)
    op.drop_index(op.f('ix__order_items__product_variant_id'), table_name='order_items', schema=schema)
    op.drop_index(op.f('ix__order_items__order_id'), table_name='order_items', schema=schema)
    op.drop_table('order_items', schema=schema)
    op.drop_index(op.f('ix__sales__cash_shift_id'), table_name='sales', schema=schema)
    op.drop_table('sales', schema=schema)
    op.drop_index(op.f('ix__purchase_items__purchase_id'), table_name='purchase_items', schema=schema)
    op.drop_index(op.f('ix__purchase_items__inventory_item_id'), table_name='purchase_items', schema=schema)
    op.drop_table('purchase_items', schema=schema)
    op.drop_index(op.f('ix__product_variants__product_id'), table_name='product_variants', schema=schema)
    op.drop_table('product_variants', schema=schema)
    op.drop_index(op.f('ix__product_option_groups__product_id'), table_name='product_option_groups', schema=schema)
    op.drop_index(op.f('ix__product_option_groups__option_group_id'), table_name='product_option_groups', schema=schema)
    op.drop_table('product_option_groups', schema=schema)
    op.drop_index(op.f('ix__options__option_group_id'), table_name='options', schema=schema)
    op.drop_table('options', schema=schema)
    op.drop_index(op.f('ix__inventory_movements__inventory_item_id'), table_name='inventory_movements', schema=schema)
    op.drop_index('idx_invmov_ref', table_name='inventory_movements', schema=schema)
    op.drop_table('inventory_movements', schema=schema)
    op.drop_index(op.f('ix__customer_orders__dining_session_id'), table_name='customer_orders', schema=schema)
    op.drop_table('customer_orders', schema=schema)
    op.drop_index(op.f('ix__cash_movements__cash_shift_id'), table_name='cash_movements', schema=schema)
    op.drop_table('cash_movements', schema=schema)
    op.drop_index(op.f('ix__cash_count_denominations__cash_shift_id'), table_name='cash_count_denominations', schema=schema)
    op.drop_table('cash_count_denominations', schema=schema)
    op.drop_index(op.f('ix__purchases__supplier_id'), table_name='purchases', schema=schema)
    op.drop_table('purchases', schema=schema)
    op.drop_index(op.f('ix__products__category_id'), table_name='products', schema=schema)
    op.drop_table('products', schema=schema)
    op.drop_index(op.f('ix__inventory_items__unit_measure_id'), table_name='inventory_items', schema=schema)
    op.drop_index(op.f('ix__inventory_items__name'), table_name='inventory_items', schema=schema)
    op.drop_table('inventory_items', schema=schema)
    op.drop_index(op.f('ix__dining_sessions__dining_table_id'), table_name='dining_sessions', schema=schema)
    op.drop_index('idx_open_session_per_table', table_name='dining_sessions', schema=schema, postgresql_where=sa.text("status = 'open'"))
    op.drop_table('dining_sessions', schema=schema)
    op.drop_index(op.f('ix__cash_shifts__cash_register_id'), table_name='cash_shifts', schema=schema)
    op.drop_index('idx_open_shift_per_register', table_name='cash_shifts', schema=schema, postgresql_where=sa.text("status = 'open'"))
    op.drop_table('cash_shifts', schema=schema)
    op.drop_index(op.f('ix__unit_measures__abbreviation'), table_name='unit_measures', schema=schema)
    op.drop_table('unit_measures', schema=schema)
    op.drop_table('suppliers', schema=schema)
    op.drop_table('payment_methods', schema=schema)
    op.drop_table('option_groups', schema=schema)
    op.drop_table('dining_tables', schema=schema)
    op.drop_index(op.f('ix__categories__name'), table_name='categories', schema=schema)
    op.drop_table('categories', schema=schema)
    op.drop_table('cash_registers', schema=schema)
    # ### end Alembic commands ###
